package com.claudiogalvaodev.moviemanager.utils.enums

enum class OscarCategory {
    BEST_PICTURE, BEST_FOREIGN_LANGUAGE_FILM, BEST_DIRECTING, BEST_ACTRESS,
    BEST_ACTOR, BEST_SUPPORTING_ACTRESS, BEST_SUPPORTING_ACTOR, BEST_ADAPTED_SCREENPLAY,
    BEST_ORIGINAL_SCREENPLAY, BEST_COSTUME_DESIGN, BEST_ORIGINAL_SCORE, BEST_ANIMATED_FEATURE_FILM,
    BEST_ANIMATED_SHORT, BEST_LIVE_ACTION_SHORT, BEST_DOCUMENTARY_FEATURE,
    BEST_DOCUMENTARY_SHORT, BEST_SOUND_MIXING, BEST_ORIGINAL_SONG, BEST_MAKEUP_AND_HAIRSTYLING,
    BEST_VISUAL_EFFECTS, BEST_CINEMATOGRAPHY, BEST_EDITING, BEST_PRODUCTION_DESIGN
}